name: Publish NuGet package

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        DOTNET_VERSION: 3.1.426
        PROJECT_FILE_PATH: src/ImgProxy/ImgProxy.csproj
        TAG_FORMAT_PREFIX: v

         # Stop wasting time caching packages
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

        # Disable sending usage data
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install tools
        run: dotnet tool restore
        
      - name: Get project version
        id: project_version
        run: |
          versionJsonOutput=`dotnet version -f "${{ env.PROJECT_FILE_PATH }}" --output-format=json`
          versionValue=`echo $versionJsonOutput | jq -r '.currentVersion'`
          echo ::set-output name=PROJECT_VERSION::$versionValue

      - name: Publish NuGet on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE_PATH }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false

      - name: Push tag
        run: |
          tag=${{ env.TAG_FORMAT_PREFIX }}${{ steps.project_version.outputs.PROJECT_VERSION}}
          git tag $tag
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" $tag
